<?php
$odbornostiMap = array(
  '1H1' => array('odbornost'=>'1H1', 'typPece'=>'S', 'oddeleni'=>'Inter'),
  '1I1' => array('odbornost'=>'1I1', 'typPece'=>'I', 'oddeleni'=>'Inter'),
  '1l1' => array('odbornost'=>'1I1', 'typPece'=>'I', 'oddeleni'=>'Inter'),  /* Překlep */
  '2H1' => array('odbornost'=>'2H1', 'typPece'=>'S', 'oddeleni'=>'Rehab'),
  '2H9' => array('odbornost'=>'2H9', 'typPece'=>'S', 'oddeleni'=>'Neuro'),
  '2I9' => array('odbornost'=>'2I9', 'typPece'=>'I', 'oddeleni'=>'Neuro'),
  '5H1' => array('odbornost'=>'5H1', 'typPece'=>'S', 'oddeleni'=>'Chiru'),
  '5HI' => array('odbornost'=>'5H1', 'typPece'=>'S', 'oddeleni'=>'Chiru'),  /* Překlep */
  '5I1' => array('odbornost'=>'5I1', 'typPece'=>'I', 'oddeleni'=>'Chiru'),
  '5l1' => array('odbornost'=>'5I1', 'typPece'=>'I', 'oddeleni'=>'Chiru'),  /* Překlep */
  '6H3' => array('odbornost'=>'6H3', 'typPece'=>'S', 'oddeleni'=>'Gynek'),
  '6H6' => array('odbornost'=>'6H6', 'typPece'=>'S', 'oddeleni'=>'Ortop'),
  '7D8' => array('odbornost'=>'7D8', 'typPece'=>'I', 'oddeleni'=>'DIP'),
  '7H5' => array('odbornost'=>'7H5', 'typPece'=>'S', 'oddeleni'=>'Ocni'),
  '7I1' => array('odbornost'=>'7I1', 'typPece'=>'I', 'oddeleni'=>'ORL'),
  '7I8' => array('odbornost'=>'7I8', 'typPece'=>'I', 'oddeleni'=>'ARO'),
  '7U8' => array('odbornost'=>'7U8', 'typPece'=>'N', 'oddeleni'=>'DIOP'),
  '9U7' => array('odbornost'=>'9U7', 'typPece'=>'N', 'oddeleni'=>'LDN'),
);

$typyInfekciMap = array(
  'infekce močového traktu'=>'IMT',
  'uroinfekce'=>'IMT',
  'močového traktu'=>'IMT',
  'inf.močového systému'=>'IMT',
  'infekce respiračního traktu'=>'IRT',
  'infekce respiračnho traktu'=>'IRT',/*překlep*/
  'inf.respiračnho systému'=>'IRT',
  'infekce dýchacího traktu'=>'IRT',
  'dolní dýchací cesty'=>'IRT',
  'dýchacího traktu'=>'IRT',
  'bronchopneumonioe'=>'IRT',
  'infekce v místě chirurgického výkonu'=>'IMChV',
  'IMC'=>'IMChV',
  'v místě chirurgického výkonu'=>'IMChV',
  'inf.v místě chirurgického výkonu'=>'IMChV',
  'infekce krevního řečiště'=>'IKR',
  'infekce krevního řečiště (IKŘ)'=>'IKR',
  'krevní řečiště'=>'IKR',
  'inf.krevního řečiště'=>'IKR',
  'v místě krevního řečiště'=>'IKR',
  'gastroenteritidy'=>'GENT',
  'střevní'=>'GENT',
  'gastrointeritida'=>'GENT',
  'gastroenteritídy'=>'GENT',
  'rotavirová enteritida'=>'GENT',
  'enterokolitida'=>'GENT',
  'CDI'=>'GENT',
  'jiná'=>'Jina',
  'ranná'=>'Jina',
  'dekubit'=>'Jina',
  'novorozenecká'=>'Jina',
  'Clostridium difficile  - Pseudomembranozní kolitida'=>'GENT',
  'clostridiová kolitida'=>'GENT',
);

$puvodciMap = array(
  'Streptococcus pyogenes'=>'StreptococcusPyogene',
  'Streptococcus pneumoniae'=>'StreptococcusPneumon',
  'Streptococcus sp. jiný'=>'Streptococcus',
  'Enterococcus faecalis'=>'EnterococcusFaecalis',
  'Enterococcus faecium'=>'EnterococcusFaecium',
  'Enterococcus sp. jiný'=>'Enterococcus',
  'Staphylococcus aureus'=>'StaphylococcusAureus',
  'Staphylococcus epidermidis'=>'StaphylococcusEpider',
  'Staphylococcus hominis'=>'StaphylococcusHomini',
  'Staphylococcus haemolyticus'=>'StaphylococcusHaemol',
  'Staphylococcus haemyolyticus'=>'StaphylococcusHaemol',
  'Staphylococcus hemolyticus'=>'StaphylococcusHaemol',
  'Staphylococcus sp. jiný'=>'Staphylococcus',
  'Escherichia coli'=>'EscherichiaColi',
  'Escherichia sp. jiná'=>'Escherichia',
  'Klebsiella pneumoniae'=>'KlebsiellaPneumoniae',
  'Klebsiella oxytoca'=>'KlebsiellaOxytoca',
  'Klebsiella sp. jiný'=>'Klebsiella',
  'Klebsiella'=>'Klebsiella',
  'Enterobacter cloacae'=>'EnterobacterCloacae',
  'Enterobacter aerogenes'=>'EnterobacterAerogene',
  'Enterobacter sp. jiný'=>'Enterobacter',
  'Serratia marcescens'=>'SerratiaMarcescens',
  'Serratia sp. jiná'=>'Serratia',
  'Proteus vulgaris'=>'ProteusVulgaris',
  'proteus vulgaris'=>'ProteusVulgaris',
  'Proteus mirabilis'=>'ProteusMirabilis',
  'Proteus sp. jiný'=>'Proteus',
  'Morganella morganii'=>'MorganellaMorgani',
  'Morganella morganii subsp. morganii'=>'MorganellaMorgani',
  'Morganella sp. jiná'=>'Morganella',
  'Salmonella enteritidis'=>'SalmonellaEnteritidi',
  'Salmonella typhimurium'=>'SalmonellaTyphimuriu',
  'Salmonella sp. jiná'=>'Salmonella',
  'Pseudomonas aeruginosa'=>'PseudomansAeruginosa',
  'Pseudomonas sp. jiná'=>'Pseudomanas',
  'Acinetobacter baumanii'=>'AcinetobacterBaumani',
  'Acinetobacter sp. jiný'=>'Acinetobacter',
  'Acinetobacter sp.'=>'Acinetobacter',
  'Acinetobacter'=>'Acinetobacter',
  'Candida albicans'=>'CandidaAlbicans',
  'Candida crusei'=>'CandidaCrusei',
  'Candida glabrata'=>'CandidaGlabrata',
  'Candida tropicalis'=>'CandidaTropicalis',
  'Candida sp. jiná'=>'Candida',
  'Candida non albicans'=>'Candida',
  'Haemophilus influenzae'=>'HaemphilusInfluenzae',
  'Neisseria meningitidis'=>'NeisseriaMeningitidi',
  'Listeria monocytogenes'=>'ListeriaMonocytogene',
  'Clostridium difficile'=>'ClostridiumDifficile',
  'clostridium difficile'=>'ClostridiumDifficile',
  'jiný'=>'Jiny',

  'toxin Clostridium difficile'=>'ClostridiumDifficile',
  'Escerichia coli'=>'EscherichiaColi',
  'E.coli'=>'EscherichiaColi',
  'Klebsiella pneumoniae subsp. pneumoniae'=>'KlebsiellaPneumoniae',
  'Staphylococcus aureus subsp. aureus'=>'StaphylococcusAureus',
  'Staphylococcus aureus MRSA'=>'StaphylococcusAureus',
  'staphylococcus epidermidis'=>'StaphylococcusEpider',
  'Staphyloccocus hominis'=>'StaphylococcusHomini',
  'Klebsiellapneumoniae.'=>'KlebsiellaPneumoniae',
  'Klebsiella pnuESBLemoniae'=>'KlebsiellaPneumoniae',
  'Klebsiella pneuESBLmoniae'=>'KlebsiellaPneumoniae',
  'Klebsiella pnemoniae'=>'KlebsiellaPneumoniae',
  'Klebsiella pneuniae'=>'KlebsiellaPneumoniae',
  'Klebsiella pneumoniae AmpC'=>'KlebsiellaPneumoniae',
  'Klebsiella pneumonie'=>'KlebsiellaPneumoniae',
  'Klebsiela pn.'=>'KlebsiellaPneumoniae',
  'Psedomonas aeruginosa'=>'PseudomansAeruginosa',
  'Escherichia coliES'=>'EscherichiaColi',
  'Escherichia coli haemolytické' => 'EscherichiaColi',
  'Streptococcus anginosus'=>'Streptococcus',
  'Streptococcus agalactiae'=>'Streptococcus',
  
  'Clostridium'=>'ClostridiumDifficile',//???
  'Clostridiun diffcile'=>'ClostridiumDifficile',

  'Streptococcus sp. Jiný'=>'Streptococcus',
  'Klebsiella'=>'Klebsiella',
  'Enterobacter sp.'=>'Enterobacter',
  'Enterobacter'=>'Enterobacter',
  'Enterobacter species'=>'Enterobacter',
  'Proteus'=>'Proteus',
  'Enterococcus'=>'Enterococcus',
  'Enterococcus species'=>'Enterococcus',
  'Pseudomonas'=>'Pseudomanas',
  'Morganella'=>'Morganella',
  'Candida'=>'Candida',
  'Staphylococcus'=>'Staphylococcus',
  'Streptococcus'=>'Streptococcus',
  'Serratia'=>'Serratia',

  'Raoutella ornitinolytica'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Raoutella ornitinolytica'),
  'Citrobacter freundii'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Citrobacter freundii'),
  'Influenza A'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Influenza A'),
  'Chlamydia pneumoniae'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Chlamydia pneumoniae'),
  'Providencia'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Providencia'),
  'Bulkhorderia'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Bulkhorderia'),
  'viry'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'viry'),
  'chřipkový virus'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'chřipkový virus'),
  'Stenotrophomonas'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Stenotrophomonas'),
  'Stenotrophomonas maltophilia'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Stenotrophomonas maltophilia'),
  'Rotaviry'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Rotaviry'),
  'rotavir'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Rotaviry'),
  'Finegoldia magna'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Finegoldia magna'),
  'anaerob'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'anaerob'),
  'není jasné'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'není jasné'),
  'nejasný'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'nejasný'),
  'neznámo'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'neznámo'),
  'Clostridium perfringens'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Clostridium perfringens'),
  'Moraxella'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Moraxella'),
  'Citrobacter'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Citrobacter'),
  'Corynebakter'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Corynebakter'),
  'uroinfekce'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Uroinfekce'),
  'Bacilus cereus'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Bacilus cereus'),
  'Burkholderia cepacia'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Burkholderia cepacia'),
  'Providentia stuartii'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Providentia stuartii'),
  'Seratia marcescens'=>array('puvodce'=>'Jiny', 'puvodceJiny'=>'Serratia marcescens'),
  
  'StaphAureus'=>'StaphylococcusAureus',
  'ProtMira'=>'ProteusMirabilis',
  'ProtVulga'=>'ProteusVulgaris',
  'MorgMorg'=>'MorganellaMorgani',
  'ESCHERCOLI'=>'EscherichiaColi',
  'StrepPyog'=>'StreptococcusPyogene',
  'KlebsPneu'=>'KlebsiellaPneumoniae',
  'EnterFaecalis'=>'EnterococcusFaecalis',
  'StaphEpi'=>'StaphylococcusEpider',
  'StaphHaemo'=>'StaphylococcusHaemol',
  'EnteroCloacae'=>'EnterobacterCloacae',
  'EnteroAero'=>'EnterobacterAerogene',
  'EnterFaecium'=>'EnterococcusFaecium',
  'PseudAerug'=>'PseudomansAeruginosa',
  'AcinBaum'=>'AcinetobacterBaumani',
  'StrepPneu'=>'StreptococcusPneumon',
  'KlebsOxy'=>'KlebsiellaOxytoca',
  'CandAlb'=>'CandidaAlbicans',
  'StaphHomi'=>'StaphylococcusHomini',
  'SerraMarces'=>'SerratiaMarcescens',
  'CandGlab'=>'CandidaGlabrata',
  'EscherColi'=>'EscherichiaColi',

  'MRSA'=>array('puvodce'=>'StaphylococcusAureus', 'rezistence'=>array('MRSA')),
  'Methicilin/Oxacilin rezistentní Staph.aureus-MRSA'=>array('puvodce'=>'StaphylococcusAureus', 'rezistence'=>array('MRSA')),

  'nezjištěn' => '',
  'neuvedeno'=>'',
  'nediagnostikován'=>'',
  'dosud není kultivace' => '',
  'není určen' => '',
);

$rezistenceMap = array(
  'AMPC'=>'AMPC',
  'AmpC'=>'AMPC',
  'MRSA'=>'MRSA',
  'ESBL'=>'ESBL',
  'betalaktamáza'=>'ESBL',
  'VRE'=>'VRE',
  'AMPC (Enterobacter)'=>array('rezistence'=>'AMPC', 'poznamka'=>'rezistence AMPC - Enterobacter'),
  'MBL'=>array('poznamka'=>'rezistence MBL'),
  'MRCNS'=>array('poznamka'=>'rezistence MRCNS'),
  'MRCSN'=>array('poznamka'=>'rezistence MRCNS'),
  'neurčeno' => ''
);

